apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2  # Adjust the number of replicas
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: ashreesee/my-react-app:v1  # Your Docker image
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "production"
